name: Build WAR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Install Maven and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            maven \
            libmaven-resources-plugin-java \
            libmaven-compiler-plugin-java \
            libmaven-war-plugin-java \
            libsurefire-java \
            libokhttp-java \
            libjackson2-databind-java \
            libxerial-sqlite-jdbc-java \
            libservlet-api-java
      - name: Build WAR
        run: mvn -o -Dmaven.repo.local=/usr/share/maven-repo -Dmaven.test.skip=true package
      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: war
          path: target/*.war
      - name: Delete old WAR artifacts
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const artifacts = await github.paginate(
              github.rest.actions.listArtifactsForRepo,
              { owner, repo, per_page: 100 }
            );
            const warArtifacts = artifacts
              .filter(a => a.name === 'war' && !a.expired)
              .sort((a, b) => new Date(b.created_at) - new Date(a.created_at));
            for (const artifact of warArtifacts.slice(3)) {
              await github.rest.actions.deleteArtifact({
                owner,
                repo,
                artifact_id: artifact.id
              });
              core.info(`Deleted artifact ${artifact.id}`);
            }

